### ISSUE TITLE
To Do #1

### ISSUE THREAD

**Issue by MarkMazel** [FlyBrainLab/NeuroMynerva#1]
From meeting of @mkturkcan  @TK-21st  and @MarkMazel  on September 27th:

**URGENT**
- [x]  Model + Model Update
   - Currently seems to be duplicating large data and causing crashes, need to pass **by ref**
- [x] Larva
   - Get ready for other species by adding Larva, requires new mesh _json_ and camera/render settings
- [x] InfoPanel
   - Fix info panel to only redraw when visible (find general way to do this for all widgets not just sidepanel)
- [x] Memory Leak(?)
   - Use Chrome front-end memory management to search for possible mem-leak
- [ ] Build Error
   - Fix error with `jupyterlab --watch` where package isnt found as well as build order for `npm`

**Following**
- [x] Floating Windows
   - Add floating window support specifically for Figures
- [x] Loading _ipynb_
   - Ability to load existing notebook into fly brain lab (probably in launcher and maybe with _.fbl_ extension)
- [ ] Multiwidget
   - Add support for multiple child widgets of same type with given master widget (and maybe even multiple master widgets?)

**Comment by TK-21st** [comment]
closed by v2 branch. feel free to reopen if necessary.
