### ISSUE TITLE
LayoutRestorer for Neu3D is very costly 

### ISSUE THREAD

**Issue by TK-21st** [FlyBrainLab/NeuroMynerva#19]
Neu3D does not get disposed of correctly even after refresh, causing memory to build up in browser.

**Comment by yiyin** [comment]
Also when the JupyterLab browser tab is closed with a lot of neurons loaded in the Neu3D window, the next time JupyterLab is opened, it tries to restore the last state and got stuck. There is a pop up window ask you if you want to keep waiting or clear workspace. Clicking on workspace does not close that pop up window so the session hangs. The JupyterLab tab needs to be closed and reopened for it to work again.

**Comment by TK-21st** [comment]
should be fixed in cd424a0205877a8cd7b1242f4f5ca563595e106c

In the current implementation, the `modelChanged` signal triggered by any fbl widget no longer causes the `layoutRestorer` to automatically store the new state of the widget. Instead, a `dirty` flag is set for the widget, which is then propogated to the `dirty` state of the entire Jlab application using the `ILabStatus` token.

The `dirty` state is reflected in a few ways, the most noticeable being that in the title bar of the neu3d widget, the close button is a filled circuit when state is dirty. The user can then save the state by either using keyboard shortcut (`Cmd+S` or `Ctrl+S` depending on platform) or using the context menu that pops up with right click.

![image](https://user-images.githubusercontent.com/26802334/97628543-39b02000-1a03-11eb-920f-fc88bdb7846d.png)

If user tries to close/refresh the window without saving, the entire JLab's application status will be dirty and consequently a pop-up window will be shown:

![image](https://user-images.githubusercontent.com/26802334/97628738-7d0a8e80-1a03-11eb-9682-23a6102b9b04.png)
