### ISSUE TITLE
To Do #2

### ISSUE THREAD

**Issue by MarkMazel** [FlyBrainLab/NeuroMynerva#2]
Prior to start of Spring 2019 semester.

**URGENT**
- [ ] Docmanager
   - Integrate current save/load prototype into JupyterLab docmanager
- [ ] Model
   - Revisit signal logic especially as to model propagation without Neu3D widget.
- [ ] Multiwidget
   - Add support for multiple child widgets of same type with given master widget (and maybe even multiple master widgets?)
- [ ] Build Error
   - Fix error with `jupyterlab --watch` where package isnt found as well as build order for `npm`

**Following**
- [ ] DevOps
   - Make packages and updates with JupyterLab more automatic
- [ ] JupyterLab Update
   - Update and stress test JupyterLab 1.0.0 upon release, should have faster build times (hopefully)
- [ ] Comms
   - Comms still has some issues, look into this.
   - Also `zmq` issues specifically appearing post load, look into this...
- [ ] Neu3D
   - Neu3D Promise propagation is wrong and needs to be fixed to allow for saving/loading of camera state.
      - Can be done for now with a manual button (?)
- [ ] Save API
   - Make the Saving JSON extendable through an API for future child widgets similar to command registry maybe
- [ ] Warnings
   - Add more support for warnings during navigation to prevent loss of work

**Comment by MarkMazel** [comment]
Warning in Product resolution for `jupyter lab` should be handled soon but is a warning and not an *error*

```
warning @neuro-mynerva/neu3d-extension > neu3d > @fortawesome/fontawesome@1.1.8: This package is deprecated. See https://git.io/fNCzJ for information about upgrading.
warning @neuro-mynerva/neu3d-extension > neu3d > @fortawesome/fontawesome-free-solid@5.0.13: This package is deprecated. See https://git.io/fNCzJ for information about upgrading.
warning @neuro-mynerva/neu3d-extension > neu3d > @fortawesome/fontawesome-free-regular@5.0.13: This package is deprecated. See https://git.io/fNCzJ for information about upgrading.
warning @neuro-mynerva/info-extension > jquery.tabulator@3.5.3: WARNING: This project has been renamed to tabulator-tables. Install using tabulator-tables instead
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
```

**Comment by MarkMazel** [comment]
JupyterLab 1.0.0 Incoming:

Does this affect us?

https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/getting_started/changelog.rst

**Comment by MarkMazel** [comment]
Still have some comm's warnings that we need to clean up, added to the "Following" section

**Comment by MarkMazel** [comment]
check if RID works?

**Comment by MarkMazel** [comment]
Better error messaging (ex: if offline and run query).

This can probably be done by forwarding error from comms?

**Comment by TK-21st** [comment]
closed by v2 branch. feel free to reopen if necessary.
