### ISSUE TITLE
Exception message during `flybrainlab.Client()` called by NeuroMynerva shall be displayed

### ISSUE THREAD

**Issue by yiyin** [FlyBrainLab/NeuroMynerva#22]
Error in the `Client` call most likely indicate a connection failure, which will yield subsequent queries fail in silence.
It would be helpful if exceptions raised in the code that execute in the background can be captured in the frontend, either as a pop-up message or in the notebook.

**Comment by yiyin** [comment]
Maybe also warnings.

**Comment by TK-21st** [comment]
closed in #30

Refer to  https://github.com/FlyBrainLab/NeuroMynerva/wiki/API-Reference for the frontend API for handling and tracking the status of client.

Front-end also is able to receive and display arbitrary information as toasts from the client.
