### ISSUE TITLE
Accessing Neuron/Neuropil List

### ISSUE THREAD

**Issue by yiyin** [FlyBrainLab/NeuroMynerva#23]
Very handy in NeuroNLP to sort through neurons/synapses but is missing in the NeuroMynerva.

**Comment by TK-21st** [comment]
@yiyin a prototype has been pushed here 9df74cf.

Let me know if this works when you have the time to try it out.

**Comment by TK-21st** [comment]
Closed for now. 

The current implementation is shown below. Each row shows the `label` of the neuron with 3 action items:

1. Toggle Visibility
2. Toggle Pin
3. Get Info

![image](https://user-images.githubusercontent.com/26802334/103685547-71839880-4f5b-11eb-9fa2-f6bcf21cb15d.png)


Feel free to re-open if there are more issues.

**Comment by yiyin** [comment]
Works great!
Can you create the same for the neuropils?

**Comment by TK-21st** [comment]
Pushed in 9268a1f2de194036ef26c3ddbc244dc5bf217b54
