### ISSUE TITLE
Error message from backend servers not displayed

### ISSUE THREAD

**Issue by yiyin** [FlyBrainLab/NeuroMynerva#25]
Also finished fetching data message from Neuroarchh server is not correctly shown.

**Comment by TK-21st** [comment]
should be partially addressed by 91ca62ecd2b9588771b75fc8591a294a9b847af4

**Comment by TK-21st** [comment]
fixed by b13e7541267eb011e0a58c6f7be8295e27947a1c.

feel free to reopen if persists.
