### ISSUE TITLE
Summary block in Info Panel

### ISSUE THREAD

**Issue by yiyin** [FlyBrainLab/NeuroMynerva#26]
Displaying some additional information (when they are available) would be useful, perhaps with a collapse button. Let's just standardize the summary block.

For a neuron:
1. Unique Name: `uname`,
2. Class: Neuron,
3. Type: `name`,
4. Datasource: `data_source`,
5. ID/Name in original dataset: `referenceId`,
6. Neurotransmitter info: 'Transmitters'
7. Additional info: `info` field which is a `dict` for additional annotations. OSN in hemibrain can be used for testing, which contains a dict like `{target_glomerulus=DM3, receptors=[OR47a, OR33b], name=ab5B, co-receptors=[Orco], sensillum=basiconica, sensillum location=antenna}`. This could include also publications and other links so these should be displayed as clickable items.
8. Morphometric info: extract from `MorphologyData` node.

For a synapse:
1. Unique Name: `uname`,
2. Class: Synapse,
3. Type: `name`,
4. Datasource: `data_source`,
5. presynaptic neuron: `uname.split('--')[0]`
6. postsynaptic neuorn: `uname.split('--')[1]`

**Comment by TK-21st** [comment]
Can we have summary information also include the neuron's `rid`? not the morphology rid but the rid of the neuron/synapse

**Comment by yiyin** [comment]
It should have been returned as `orid`

**Comment by yiyin** [comment]
edited 5 and 6 in synapse.

**Comment by TK-21st** [comment]
> It should have been returned as `orid`

the `orid` seems to be pointing to the `MorphologyData` node instead of the `Neuron` node.

**Comment by yiyin** [comment]
What's the steps?

**Comment by TK-21st** [comment]
mostly addressed by f228cbe8e9a5b6a7753fa2fb84889583a4248724

**Comment by TK-21st** [comment]
All done in b26dcf354f7b5d20c284499789b9dbbfdcca97ae
