### ISSUE TITLE
Delete button in Neu3D

### ISSUE THREAD

**Issue by yiyin** [FlyBrainLab/NeuroMynerva#35]
In addition to removing all visualized neurons and synapses in the window, it should also fire a query to the backend to clear the state.

**Comment by TK-21st** [comment]
Addressed in 7c6b2467e8d2753462c57a0f2a1c6047fdee2a53.

Note that `removeByUname` is used instead of `removeByRid`. See https://github.com/FlyBrainLab/NeuroMynerva/commit/7c6b2467e8d2753462c57a0f2a1c6047fdee2a53#r45500306.
