### ISSUE TITLE
NLP performance issue

### ISSUE THREAD

**Issue by TK-21st** [FlyBrainLab/NeuroMynerva#39]
Large queries hang the browser. could be a debounce issue.

**Comment by TK-21st** [comment]
None of debouncing, throttling or using timeout are going to fix this. 
Will need to use lazy rendering with things like tabulator or react table. The issue is from rendering a table that's too large.

**Comment by TK-21st** [comment]
should be addressed by a4b12e59669c6f65417931992236dc361312f29a

**Comment by yiyin** [comment]
How do I remove the neuron/neuropil from the list?

**Comment by TK-21st** [comment]
> How do I remove the neuron/neuropil from the list?

Just added the features in 36b8d5c4b52986ffbf3a0a60b6d178c32a9ad78d

**Comment by TK-21st** [comment]
Should be addressed by the latest commits on `master`.
Feel free to re-open the issue if problem persists.
