### ISSUE TITLE
Neuropil mesh directly from database

### ISSUE THREAD

**Issue by yiyin** [FlyBrainLab/NeuroMynerva#41]
The following query should directly send Neuropil mesh data to Neu3D widget.
```python
res = client.executeNAquery('query: [{'action': {'method': {'query': {}}}, 
                                                 'object': {'class': 'Neuropil'}}
                                    ],
                            'format': 'morphology'})
```
can be use that to show Neuropil meshes so Neuromynerva no longer needs to depend on separate, static files.

**Comment by yiyin** [comment]
Perhaps also 
```python
res = client.executeNAquery('query: [{'action': {'method': {'query': {}}}, 
                                                 'object': {'class': 'Subregion'}}
                                    ],
                            'format': 'morphology'})
```
but hide them by default so they can also be toggled to see, for example, individual glomerulus.

**Comment by TK-21st** [comment]
Try the [`mesh_from_db`](https://github.com/FlyBrainLab/NeuroMynerva/tree/mesh_from_db) branch. 

It's work in progress and state persistence is not working for the meshes but the meshes can be loaded using the code below:
```python
res = client.executeNAquery({
    'query':[{'action': {'method': {'query': {}}}, 
              'object': {'class': 'Neuropil'}
             }],
    'format': 'morphology'})
```

**Comment by TK-21st** [comment]
state persistence working as of 84f069bea8877cc9519aefc12902680ad5b08328.

**Comment by TK-21st** [comment]
closed as addressed in v2.
