### ISSUE TITLE
Short Term To Dos

### ISSUE THREAD

**Issue by mkturkcan** [FlyBrainLab/NeuroMynerva#6]
Some important considerations to address this week:
- JSONEditor requires a major overhaul. Possibly requires removal or redesign. In its current incarnation, it not interactive enough.
- Workspace saving/loading needs to be turned into buttons in the user interface.
- Try to integrate the upcoming version of Neu3D with performance improvements for low end machines.

**Comment by TK-21st** [comment]
closed by update to v2 branch. feel free to reopen if necessary
